/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SpiralTile {
  x: number
  y: number
}
export declare function renderSpiralRouteFromStore(snapshotJson: string): string
export declare function renderSpiralRouteFromTiles(tiles: Array<SpiralTile>): string
export declare function renderCounterBodyFromStore(snapshotJson: string): string
export declare function renderBodyFromIr(renderIrJson: string, snapshotJson: string, bindingsJson: string): string
